import type {
  ActivityEvent,
  Agent,
  EscrowTransaction,
  Goal,
  UserPreferences,
  WorkflowTask,
} from "@/lib/types";
import { simulatedHoursAgo } from "@/lib/simulation-clock";

export const DEMO_USER_ID = "demo-user";

export const MOCK_USER_PREFERENCES: UserPreferences = {
  userId: DEMO_USER_ID,
  budget: 2000,
  timezone: "UTC",
  preferredStack: "Next.js, Solidity",
  favoriteAgentIds: ["agt-atlas-research", "agt-ledger-forge"],
  walletAddress: null,
};

export const MOCK_AGENTS: Agent[] = [
  {
    id: "agt-atlas-research",
    name: "Atlas Research Co.",
    avatarUrl: null,
    tagline: "Market & technical research for fast-moving launches",
    bio: "Atlas runs deep-dive market, competitor, and feasibility research, turning a one-line goal into a validated brief within hours.",
    specializations: ["Research"],
    rating: 4.9,
    completedJobs: 212,
    pricePerTask: 180,
    etaHours: 6,
    availability: "available",
    joinedAt: "2025-02-11T00:00:00.000Z",
  },
  {
    id: "agt-nova-design",
    name: "Nova Design Studio",
    avatarUrl: null,
    tagline: "Brand & product design for Web3-native launches",
    bio: "Nova ships full identity systems, landing pages, and product UI with an obsessive focus on premium visual polish.",
    specializations: ["Product Design"],
    rating: 4.8,
    completedJobs: 189,
    pricePerTask: 240,
    etaHours: 10,
    availability: "available",
    joinedAt: "2025-01-22T00:00:00.000Z",
  },
  {
    id: "agt-ledger-forge",
    name: "Ledger Forge",
    avatarUrl: null,
    tagline: "Smart contract engineering, audited defaults included",
    bio: "Ledger Forge writes and deploys production Solidity, defaulting to audited, gas-optimized patterns for every contract.",
    specializations: ["Smart Contracts"],
    rating: 4.9,
    completedJobs: 340,
    pricePerTask: 520,
    etaHours: 18,
    availability: "busy",
    joinedAt: "2024-11-03T00:00:00.000Z",
  },
  {
    id: "agt-sentinel-audit",
    name: "SentinelAudit",
    avatarUrl: null,
    tagline: "Independent smart contract security review",
    bio: "SentinelAudit performs manual + automated security review against the top exploit classes before anything touches mainnet.",
    specializations: ["Security Audit"],
    rating: 5.0,
    completedJobs: 98,
    pricePerTask: 890,
    etaHours: 24,
    availability: "available",
    joinedAt: "2025-03-14T00:00:00.000Z",
  },
  {
    id: "agt-growthwave",
    name: "Growthwave Collective",
    avatarUrl: null,
    tagline: "Launch marketing & growth campaigns",
    bio: "Growthwave plans and executes go-to-market campaigns across socials, press, and paid channels.",
    specializations: ["Growth Marketing"],
    rating: 4.6,
    completedJobs: 275,
    pricePerTask: 310,
    etaHours: 12,
    availability: "available",
    joinedAt: "2025-01-05T00:00:00.000Z",
  },
  {
    id: "agt-shipyard-devops",
    name: "Shipyard DevOps",
    avatarUrl: null,
    tagline: "Deployment, infra, and release engineering",
    bio: "Shipyard handles CI/CD, infra provisioning, and production deploys so launches ship without surprises.",
    specializations: ["DevOps & Deployment"],
    rating: 4.7,
    completedJobs: 156,
    pricePerTask: 260,
    etaHours: 8,
    availability: "available",
    joinedAt: "2025-02-27T00:00:00.000Z",
  },
  {
    id: "agt-lexicon-legal",
    name: "Lexicon Legal",
    avatarUrl: null,
    tagline: "Compliance review for token & product launches",
    bio: "Lexicon reviews terms, token classification risk, and jurisdictional compliance before public launch.",
    specializations: ["Legal & Compliance"],
    rating: 4.8,
    completedJobs: 87,
    pricePerTask: 410,
    etaHours: 20,
    availability: "busy",
    joinedAt: "2024-12-19T00:00:00.000Z",
  },
  {
    id: "agt-quillwork",
    name: "Quillwork Studio",
    avatarUrl: null,
    tagline: "Copywriting & content at speed",
    bio: "Quillwork produces landing copy, docs, and content calendars tuned to your brand voice.",
    specializations: ["Content & Copy"],
    rating: 4.7,
    completedJobs: 421,
    pricePerTask: 95,
    etaHours: 4,
    availability: "available",
    joinedAt: "2024-10-08T00:00:00.000Z",
  },
  {
    id: "agt-datastream",
    name: "Datastream Analytics",
    avatarUrl: null,
    tagline: "Data pipelines & performance analysis",
    bio: "Datastream instruments products and campaigns, then reports back what's actually moving the numbers.",
    specializations: ["Data Analysis"],
    rating: 4.9,
    completedJobs: 198,
    pricePerTask: 220,
    etaHours: 9,
    availability: "available",
    joinedAt: "2025-02-02T00:00:00.000Z",
  },
  {
    id: "agt-beacon-community",
    name: "Beacon Community",
    avatarUrl: null,
    tagline: "Community seeding & moderation",
    bio: "Beacon stands up Discord/Telegram communities and keeps them healthy through launch and beyond.",
    specializations: ["Community Management"],
    rating: 4.5,
    completedJobs: 132,
    pricePerTask: 150,
    etaHours: 5,
    availability: "available",
    joinedAt: "2025-03-01T00:00:00.000Z",
  },
  {
    id: "agt-prism-research",
    name: "Prism Research Labs",
    avatarUrl: null,
    tagline: "Academic-grade research for technical products",
    bio: "Prism specializes in rigorous technical literature review and feasibility studies.",
    specializations: ["Research", "Data Analysis"],
    rating: 4.7,
    completedJobs: 143,
    pricePerTask: 210,
    etaHours: 7,
    availability: "offline",
    joinedAt: "2025-01-30T00:00:00.000Z",
  },
  {
    id: "agt-circuit-contracts",
    name: "Circuit Smart Contracts",
    avatarUrl: null,
    tagline: "Fast-turnaround Solidity for MVPs",
    bio: "Circuit builds lean, tested contracts for teams that need to move from spec to testnet in days.",
    specializations: ["Smart Contracts"],
    rating: 4.6,
    completedJobs: 176,
    pricePerTask: 480,
    etaHours: 16,
    availability: "available",
    joinedAt: "2025-02-18T00:00:00.000Z",
  },
  {
    id: "agt-vantage-design",
    name: "Vantage Design Co.",
    avatarUrl: null,
    tagline: "End-to-end product design systems",
    bio: "Vantage builds design systems that scale from landing page to full product surface.",
    specializations: ["Product Design"],
    rating: 4.9,
    completedJobs: 267,
    pricePerTask: 290,
    etaHours: 11,
    availability: "available",
    joinedAt: "2024-11-25T00:00:00.000Z",
  },
  {
    id: "agt-northstar-marketing",
    name: "Northstar Marketing",
    avatarUrl: null,
    tagline: "Full-funnel growth for token launches",
    bio: "Northstar runs paid acquisition and community-led growth loops for Web3 launches.",
    specializations: ["Growth Marketing"],
    rating: 4.8,
    completedJobs: 310,
    pricePerTask: 350,
    etaHours: 14,
    availability: "available",
    joinedAt: "2025-01-14T00:00:00.000Z",
  },
];

export const MOCK_GOALS: Goal[] = [
  {
    id: "goal-launch-nft",
    userId: DEMO_USER_ID,
    title: "Launch my NFT collection",
    status: "in_progress",
    budget: 3200,
    createdAt: "2026-07-02T09:15:00.000Z",
  },
  {
    id: "goal-newsletter-growth",
    userId: DEMO_USER_ID,
    title: "Grow my dev newsletter to 10k subscribers",
    status: "planning",
    budget: 900,
    createdAt: "2026-07-08T14:40:00.000Z",
  },
];

export const MOCK_WORKFLOW_TASKS: WorkflowTask[] = [
  {
    id: "task-nft-research",
    goalId: "goal-launch-nft",
    title: "Research",
    description: "Market landscape, comparable collections, and mint mechanics.",
    order: 0,
    dependsOn: [],
    status: "paid",
    specialization: "Research",
    agentId: "agt-atlas-research",
    price: 180,
    etaHours: 6,
    trustScore: 82,
    matchRationale: "strong quality rating and availability",
    startedAt: simulatedHoursAgo(20),
    reviewStartedAt: simulatedHoursAgo(6),
  },
  {
    id: "task-nft-design",
    goalId: "goal-launch-nft",
    title: "Design",
    description: "Collection art direction, trait system, and landing page design.",
    order: 1,
    dependsOn: ["task-nft-research"],
    status: "completed",
    specialization: "Product Design",
    agentId: "agt-nova-design",
    price: 240,
    etaHours: 10,
    trustScore: 90,
    matchRationale: "strong quality rating and price fit",
    startedAt: simulatedHoursAgo(16),
    reviewStartedAt: simulatedHoursAgo(2),
  },
  {
    id: "task-nft-contract",
    goalId: "goal-launch-nft",
    title: "Smart Contract",
    description: "ERC-721A mint contract with allowlist and royalty support.",
    order: 2,
    dependsOn: ["task-nft-design"],
    status: "running",
    specialization: "Smart Contracts",
    agentId: "agt-ledger-forge",
    price: 520,
    etaHours: 18,
    trustScore: 84,
    matchRationale: "strong quality rating and track record",
    startedAt: simulatedHoursAgo(16),
    reviewStartedAt: null,
  },
  {
    id: "task-nft-audit",
    goalId: "goal-launch-nft",
    title: "Audit",
    description: "Independent security review of the mint contract before deploy.",
    order: 3,
    dependsOn: ["task-nft-contract"],
    status: "pending",
    specialization: "Security Audit",
    agentId: "agt-sentinel-audit",
    price: 890,
    etaHours: 24,
    trustScore: 88,
    matchRationale: "strong quality rating and availability",
    startedAt: null,
    reviewStartedAt: null,
  },
  {
    id: "task-nft-marketing",
    goalId: "goal-launch-nft",
    title: "Marketing",
    description: "Launch campaign across X, Discord, and press outreach.",
    order: 4,
    dependsOn: ["task-nft-design"],
    status: "review",
    specialization: "Growth Marketing",
    agentId: "agt-growthwave",
    price: 310,
    etaHours: 12,
    trustScore: 76,
    matchRationale: "strong quality rating and availability",
    startedAt: simulatedHoursAgo(12.5),
    reviewStartedAt: simulatedHoursAgo(0.5),
  },
  {
    id: "task-nft-deploy",
    goalId: "goal-launch-nft",
    title: "Deploy",
    description: "Mainnet deployment, verification, and mint site go-live.",
    order: 5,
    dependsOn: ["task-nft-audit", "task-nft-marketing"],
    status: "pending",
    specialization: "DevOps & Deployment",
    agentId: "agt-shipyard-devops",
    price: 260,
    etaHours: 8,
    trustScore: 81,
    matchRationale: "strong quality rating and availability",
    startedAt: null,
    reviewStartedAt: null,
  },
  {
    id: "task-newsletter-content",
    goalId: "goal-newsletter-growth",
    title: "Content Strategy",
    description: "3-month content calendar tuned for developer audiences.",
    order: 0,
    dependsOn: [],
    status: "pending",
    specialization: "Content & Copy",
    agentId: "agt-quillwork",
    price: 95,
    etaHours: 4,
    trustScore: 85,
    matchRationale: "strong quality rating and track record",
    startedAt: null,
    reviewStartedAt: null,
  },
  {
    id: "task-newsletter-community",
    goalId: "goal-newsletter-growth",
    title: "Community Seeding",
    description: "Seed initial subscriber base via dev communities.",
    order: 1,
    dependsOn: [],
    status: "pending",
    specialization: "Community Management",
    agentId: "agt-beacon-community",
    price: 150,
    etaHours: 5,
    trustScore: 73,
    matchRationale: "strong quality rating and availability",
    startedAt: null,
    reviewStartedAt: null,
  },
];

export const MOCK_ESCROW_TRANSACTIONS: EscrowTransaction[] = [
  {
    id: "escrow-nft-research",
    taskId: "task-nft-research",
    agentId: "agt-atlas-research",
    amount: 180,
    status: "released",
    createdAt: "2026-07-02T09:20:00.000Z",
    releasedAt: "2026-07-02T15:40:00.000Z",
  },
  {
    id: "escrow-nft-design",
    taskId: "task-nft-design",
    agentId: "agt-nova-design",
    amount: 240,
    status: "locked",
    createdAt: "2026-07-02T15:45:00.000Z",
    releasedAt: null,
  },
  {
    id: "escrow-nft-contract",
    taskId: "task-nft-contract",
    agentId: "agt-ledger-forge",
    amount: 520,
    status: "locked",
    createdAt: "2026-07-04T10:00:00.000Z",
    releasedAt: null,
  },
  {
    id: "escrow-nft-marketing",
    taskId: "task-nft-marketing",
    agentId: "agt-growthwave",
    amount: 310,
    status: "locked",
    createdAt: "2026-07-05T11:30:00.000Z",
    releasedAt: null,
  },
];

export const MOCK_ACTIVITY_EVENTS: ActivityEvent[] = [
  {
    id: "evt-1",
    type: "goal_created",
    message: "Goal created: “Launch my NFT collection”",
    createdAt: "2026-07-02T09:15:00.000Z",
    goalId: "goal-launch-nft",
    agentId: null,
  },
  {
    id: "evt-2",
    type: "agent_matched",
    message: "Atlas Research Co. matched to Research",
    createdAt: "2026-07-02T09:18:00.000Z",
    goalId: "goal-launch-nft",
    agentId: "agt-atlas-research",
  },
  {
    id: "evt-3",
    type: "escrow_locked",
    message: "Escrow locked for Research ($180)",
    createdAt: "2026-07-02T09:20:00.000Z",
    goalId: "goal-launch-nft",
    agentId: "agt-atlas-research",
  },
  {
    id: "evt-4",
    type: "task_delivered",
    message: "Research delivered by Atlas Research Co.",
    createdAt: "2026-07-02T15:35:00.000Z",
    goalId: "goal-launch-nft",
    agentId: "agt-atlas-research",
  },
  {
    id: "evt-5",
    type: "escrow_released",
    message: "Escrow released to Atlas Research Co. ($180)",
    createdAt: "2026-07-02T15:40:00.000Z",
    goalId: "goal-launch-nft",
    agentId: "agt-atlas-research",
  },
  {
    id: "evt-6",
    type: "agent_matched",
    message: "Nova Design Studio matched to Design",
    createdAt: "2026-07-02T15:45:00.000Z",
    goalId: "goal-launch-nft",
    agentId: "agt-nova-design",
  },
  {
    id: "evt-7",
    type: "task_delivered",
    message: "Design delivered by Nova Design Studio",
    createdAt: "2026-07-04T09:05:00.000Z",
    goalId: "goal-launch-nft",
    agentId: "agt-nova-design",
  },
  {
    id: "evt-8",
    type: "agent_matched",
    message: "Ledger Forge matched to Smart Contract",
    createdAt: "2026-07-04T10:00:00.000Z",
    goalId: "goal-launch-nft",
    agentId: "agt-ledger-forge",
  },
  {
    id: "evt-9",
    type: "task_started",
    message: "Ledger Forge started Smart Contract",
    createdAt: "2026-07-04T10:05:00.000Z",
    goalId: "goal-launch-nft",
    agentId: "agt-ledger-forge",
  },
  {
    id: "evt-10",
    type: "agent_matched",
    message: "Growthwave Collective matched to Marketing",
    createdAt: "2026-07-05T11:30:00.000Z",
    goalId: "goal-launch-nft",
    agentId: "agt-growthwave",
  },
  {
    id: "evt-11",
    type: "goal_created",
    message: "Goal created: “Grow my dev newsletter to 10k subscribers”",
    createdAt: "2026-07-08T14:40:00.000Z",
    goalId: "goal-newsletter-growth",
    agentId: null,
  },
];
